import Datatable from "@/components/admin/datatable/Datatable";
import { Button } from "@/components/ui/button";
import BiBreadcrumb from "@/components/ui/common/BiBreadcrumb";
import PageHeader from "@/components/ui/common/PageHeader";
import React from "react";
import { productListColumns } from "./components/ProductListColums";
import Link from "next/link";
const dataDemo = [
  // ---------- PROFILE (SH models) ----------
  {
    id: "p001",
    model: "SH-2001",
    brand: "Flybird",
    size: "3048",
    size_type: "mm",
    finish: "Ceramic Gold",
    mrp: "2380",
    category: "Profile",
  },
  {
    id: "p002",
    model: "SH-2006",
    brand: "Alstone",
    size: "2440",
    size_type: "mm",
    finish: "Matte Black",
    mrp: "2190",
    category: "Profile",
  },
  {
    id: "p003",
    model: "SH-2007",
    brand: "Eurobond",
    size: "3050",
    size_type: "mm",
    finish: "Rose Gold",
    mrp: "2870",
    category: "Profile",
  },
  {
    id: "p004",
    model: "SH-2026",
    brand: "Flybird",
    size: "1220x2440",
    size_type: "mm",
    finish: "Champagne Bronze",
    mrp: "3150",
    category: "Profile",
  },
  {
    id: "p005",
    model: "SH-2001",
    brand: "Aludecor",
    size: "3048",
    size_type: "mm",
    finish: "Silver Grey",
    mrp: "2250",
    category: "Profile",
  },
  {
    id: "p006",
    model: "SH-2006",
    brand: "Flybird",
    size: "2440",
    size_type: "mm",
    finish: "Glossy White",
    mrp: "1980",
    category: "Profile",
  },
  {
    id: "p007",
    model: "SH-2007",
    brand: "Alstone",
    size: "3050",
    size_type: "mm",
    finish: "Ceramic Gold",
    mrp: "2690",
    category: "Profile",
  },
  {
    id: "p008",
    model: "SH-2026",
    brand: "Eurobond",
    size: "3048",
    size_type: "mm",
    finish: "Matte Black",
    mrp: "2310",
    category: "Profile",
  },
  {
    id: "p009",
    model: "SH-2001",
    brand: "Flybird",
    size: "2440",
    size_type: "mm",
    finish: "Rose Gold",
    mrp: "2950",
    category: "Profile",
  },
  {
    id: "p010",
    model: "SH-2006",
    brand: "Aludecor",
    size: "3050",
    size_type: "mm",
    finish: "Champagne Bronze",
    mrp: "3180",
    category: "Profile",
  },

  {
    id: "p011",
    model: "SH-2007",
    brand: "Flybird",
    size: "3048",
    size_type: "mm",
    finish: "Silver Grey",
    mrp: "2210",
    category: "Profile",
  },
  {
    id: "p012",
    model: "SH-2026",
    brand: "Alstone",
    size: "2440",
    size_type: "mm",
    finish: "Glossy White",
    mrp: "2050",
    category: "Profile",
  },
  {
    id: "p013",
    model: "SH-2001",
    brand: "Eurobond",
    size: "3050",
    size_type: "mm",
    finish: "Ceramic Gold",
    mrp: "2820",
    category: "Profile",
  },
  {
    id: "p014",
    model: "SH-2006",
    brand: "Flybird",
    size: "3048",
    size_type: "mm",
    finish: "Matte Black",
    mrp: "2270",
    category: "Profile",
  },
  {
    id: "p015",
    model: "SH-2007",
    brand: "Aludecor",
    size: "2440",
    size_type: "mm",
    finish: "Rose Gold",
    mrp: "2910",
    category: "Profile",
  },

  {
    id: "p016",
    model: "SH-2026",
    brand: "Flybird",
    size: "3050",
    size_type: "mm",
    finish: "Silver Grey",
    mrp: "2190",
    category: "Profile",
  },
  {
    id: "p017",
    model: "SH-2001",
    brand: "Alstone",
    size: "3048",
    size_type: "mm",
    finish: "Champagne Bronze",
    mrp: "3120",
    category: "Profile",
  },
  {
    id: "p018",
    model: "SH-2006",
    brand: "Eurobond",
    size: "2440",
    size_type: "mm",
    finish: "Glossy White",
    mrp: "1970",
    category: "Profile",
  },
  {
    id: "p019",
    model: "SH-2007",
    brand: "Flybird",
    size: "3050",
    size_type: "mm",
    finish: "Ceramic Gold",
    mrp: "2740",
    category: "Profile",
  },
  {
    id: "p020",
    model: "SH-2026",
    brand: "Aludecor",
    size: "3048",
    size_type: "mm",
    finish: "Matte Black",
    mrp: "2330",
    category: "Profile",
  },

  // ---------- DOOR HANDLE (9481) ----------
  {
    id: "d021",
    model: "9481",
    brand: "Flybird",
    size: "8inch",
    size_type: "inch",
    finish: "Silver Grey",
    mrp: "1450",
    category: "Door Handle",
  },
  {
    id: "d022",
    model: "9481",
    brand: "Alstone",
    size: "10inch",
    size_type: "inch",
    finish: "Matte Black",
    mrp: "1680",
    category: "Door Handle",
  },
  {
    id: "d023",
    model: "9481",
    brand: "Eurobond",
    size: "12inch",
    size_type: "inch",
    finish: "Rose Gold",
    mrp: "1890",
    category: "Door Handle",
  },
  {
    id: "d024",
    model: "9481",
    brand: "Flybird",
    size: "8inch",
    size_type: "inch",
    finish: "Champagne Bronze",
    mrp: "1720",
    category: "Door Handle",
  },
  {
    id: "d025",
    model: "9481",
    brand: "Aludecor",
    size: "10inch",
    size_type: "inch",
    finish: "Glossy White",
    mrp: "1550",
    category: "Door Handle",
  },
  {
    id: "d026",
    model: "9481",
    brand: "Eurobond",
    size: "8inch",
    size_type: "inch",
    finish: "Silver Grey",
    mrp: "1490",
    category: "Door Handle",
  },
  {
    id: "d027",
    model: "9481",
    brand: "Flybird",
    size: "12inch",
    size_type: "inch",
    finish: "Matte Black",
    mrp: "1820",
    category: "Door Handle",
  },
  {
    id: "d028",
    model: "9481",
    brand: "Alstone",
    size: "10inch",
    size_type: "inch",
    finish: "Rose Gold",
    mrp: "1760",
    category: "Door Handle",
  },
  {
    id: "d029",
    model: "9481",
    brand: "Eurobond",
    size: "12inch",
    size_type: "inch",
    finish: "Champagne Bronze",
    mrp: "1910",
    category: "Door Handle",
  },
  {
    id: "d030",
    model: "9481",
    brand: "Flybird",
    size: "8inch",
    size_type: "inch",
    finish: "Glossy White",
    mrp: "1580",
    category: "Door Handle",
  },

  // ---------- CABINET HANDLE (Boot / I20 / Jems / Arrow) ----------
  {
    id: "c031",
    model: "Boot",
    brand: "Flybird",
    size: "160",
    size_type: "mm",
    finish: "Matte Black",
    mrp: "420",
    category: "Cabinet Handle",
  },
  {
    id: "c032",
    model: "I20",
    brand: "Alstone",
    size: "192",
    size_type: "mm",
    finish: "Rose Gold",
    mrp: "520",
    category: "Cabinet Handle",
  },
  {
    id: "c033",
    model: "Jems",
    brand: "Eurobond",
    size: "224",
    size_type: "mm",
    finish: "Champagne Bronze",
    mrp: "610",
    category: "Cabinet Handle",
  },
  {
    id: "c034",
    model: "Arrow",
    brand: "Flybird",
    size: "256",
    size_type: "mm",
    finish: "Silver Grey",
    mrp: "580",
    category: "Cabinet Handle",
  },
  {
    id: "c035",
    model: "Boot",
    brand: "Aludecor",
    size: "160",
    size_type: "mm",
    finish: "Glossy White",
    mrp: "460",
    category: "Cabinet Handle",
  },

  {
    id: "c036",
    model: "I20",
    brand: "Flybird",
    size: "192",
    size_type: "mm",
    finish: "Matte Black",
    mrp: "490",
    category: "Cabinet Handle",
  },
  {
    id: "c037",
    model: "Jems",
    brand: "Alstone",
    size: "224",
    size_type: "mm",
    finish: "Ceramic Gold",
    mrp: "640",
    category: "Cabinet Handle",
  },
  {
    id: "c038",
    model: "Arrow",
    brand: "Eurobond",
    size: "256",
    size_type: "mm",
    finish: "Rose Gold",
    mrp: "610",
    category: "Cabinet Handle",
  },
  {
    id: "c039",
    model: "Boot",
    brand: "Flybird",
    size: "128",
    size_type: "mm",
    finish: "Silver Grey",
    mrp: "390",
    category: "Cabinet Handle",
  },
  {
    id: "c040",
    model: "I20",
    brand: "Aludecor",
    size: "192",
    size_type: "mm",
    finish: "Glossy White",
    mrp: "510",
    category: "Cabinet Handle",
  },

  {
    id: "c041",
    model: "Jems",
    brand: "Flybird",
    size: "224",
    size_type: "mm",
    finish: "Matte Black",
    mrp: "600",
    category: "Cabinet Handle",
  },
  {
    id: "c042",
    model: "Arrow",
    brand: "Alstone",
    size: "256",
    size_type: "mm",
    finish: "Ceramic Gold",
    mrp: "650",
    category: "Cabinet Handle",
  },
  {
    id: "c043",
    model: "Boot",
    brand: "Eurobond",
    size: "160",
    size_type: "mm",
    finish: "Rose Gold",
    mrp: "470",
    category: "Cabinet Handle",
  },
  {
    id: "c044",
    model: "I20",
    brand: "Flybird",
    size: "192",
    size_type: "mm",
    finish: "Silver Grey",
    mrp: "500",
    category: "Cabinet Handle",
  },
  {
    id: "c045",
    model: "Jems",
    brand: "Aludecor",
    size: "224",
    size_type: "mm",
    finish: "Champagne Bronze",
    mrp: "630",
    category: "Cabinet Handle",
  },

  {
    id: "c046",
    model: "Arrow",
    brand: "Flybird",
    size: "256",
    size_type: "mm",
    finish: "Glossy White",
    mrp: "590",
    category: "Cabinet Handle",
  },
  {
    id: "c047",
    model: "Boot",
    brand: "Alstone",
    size: "160",
    size_type: "mm",
    finish: "Matte Black",
    mrp: "430",
    category: "Cabinet Handle",
  },
  {
    id: "c048",
    model: "I20",
    brand: "Eurobond",
    size: "192",
    size_type: "mm",
    finish: "Rose Gold",
    mrp: "540",
    category: "Cabinet Handle",
  },
  {
    id: "c049",
    model: "Jems",
    brand: "Flybird",
    size: "224",
    size_type: "mm",
    finish: "Silver Grey",
    mrp: "610",
    category: "Cabinet Handle",
  },
  {
    id: "c050",
    model: "Arrow",
    brand: "Aludecor",
    size: "256",
    size_type: "mm",
    finish: "Matte Black",
    mrp: "600",
    category: "Cabinet Handle",
  },
];

const page = () => {
  return (
    <div className="max-w-9xl mx-auto gap-4 grid">
      <BiBreadcrumb />
      <PageHeader
        title="Products"
        description="Realtime Products Sanpshot"
        action={
          <Button asChild variant={"outline"}>
            <Link href={"/admin/products/create"}>Add Product</Link>
          </Button>
        }
      />
      <Datatable columns={productListColumns} data={dataDemo} />
    </div>
  );
};

export default page;
