import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Toaster } from "sonner";
import QueryProvider from "@/providers/query-provider";
import Container from "@/components/layout/container";
import { TopLoadingBar } from "@/components/ui/top-loading-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hini | Premium Hardware Collection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`
      ${geistSans.variable}
      ${geistMono.variable}
      antialiased
      min-h-screen
      bg-background
      text-foreground
      font-sans
    `}
      >
        <QueryProvider>
          <TopLoadingBar />
          <div className="min-h-screen bg-white dark:bg-black text-black dark:text-white">
            {children}
            <Toaster />
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
